### ISSUE TITLE
Enabled shared volume for mysql

### ISSUE THREAD

**Issue by rdok** [rdok/gr-embassy-bookings-notifier#11]
With the current (commented out) docker configuration when attempting to compose up the following permissions is thrown:

```
$ docker-compose -f docker-compose.yml -f docker/development.yml up  -d --build --remove-orphans 
Building php-service

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.24.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 127, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 1085, in up
    to_attach = up(False)
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 1081, in up
    silent=options.get('--quiet-pull'),
  File "/usr/lib/python3.7/site-packages/compose/project.py", line 527, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent)
  File "/usr/lib/python3.7/site-packages/compose/service.py", line 344, in ensure_image_exists
    self.build()
  File "/usr/lib/python3.7/site-packages/compose/service.py", line 1084, in build
    platform=self.platform,
  File "/usr/lib/python3.7/site-packages/docker/api/build.py", line 160, in build
    path, exclude=exclude, dockerfile=dockerfile, gzip=gzip
  File "/usr/lib/python3.7/site-packages/docker/utils/build.py", line 30, in tar
    files=sorted(exclude_paths(root, exclude, dockerfile=dockerfile[0])),
  File "/usr/lib/python3.7/site-packages/docker/utils/build.py", line 49, in exclude_paths
    return set(pm.walk(root))
  File "/usr/lib/python3.7/site-packages/docker/utils/build.py", line 214, in rec_walk
    for sub in rec_walk(cur):
  File "/usr/lib/python3.7/site-packages/docker/utils/build.py", line 214, in rec_walk
    for sub in rec_walk(cur):
  File "/usr/lib/python3.7/site-packages/docker/utils/build.py", line 214, in rec_walk
    for sub in rec_walk(cur):
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.7/site-packages/docker/utils/build.py", line 184, in rec_walk
    for f in os.listdir(current_dir):
PermissionError: [Errno 13] Permission denied: '/home/rdok/Code/gr-embassy-bookings-notifier/docker/mysql/lib/#innodb_temp'
```

**Comment by rdok** [comment]
Resolved by https://github.com/rdok/gr-embassy-bookings-notifier/blob/master/docker/php/Dockerfile#L12

That is, the host adds it's uid to the $USER_ID environment variable. 

Thus, when files are modified in docker, the new docker user will have the same uid, and thus resolving this issues.
